# Generated by Django 3.2.25 on 2025-03-19 11:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('checkout', '0002_rename_original_bag_order_original_cart'),
    ]

    operations = [
        migrations.RenameField(
            model_name='order',
            old_name='user_profile',
            new_name='user',
        ),
    ]
