# Generated by Django 3.2.25 on 2025-02-24 08:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='is_favourite',
            field=models.BooleanField(default=False),
        ),
    ]
